//
// Created by hal9000 on 2/22/24.
//

#ifndef ALTAIRINTERVIEW_ALGORITHMSTIMECOMPARISONTEST_H
#define ALTAIRINTERVIEW_ALGORITHMSTIMECOMPARISONTEST_H
#include "Test.h"


#endif //ALTAIRINTERVIEW_ALGORITHMSTIMECOMPARISONTEST_H
